services:
  server:
    build: .

    ports:
      - "8080:8080"

    env_file:
      - .env.development.local

    depends_on:
      - redis

  redis:
    image: redis:7.4-alpine

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

volumes:
  redis-data:
